### PR TITLE
DataMatrix: support fixed rows and columns count

### LINKED ISSUE #8: [Feature] [DataMatrix] Support fixed row and column count
Add feature for fixed rows and columns count in data matrix code.

### PR DESCRIPTION
**Pull request by Int32Overflow**
I'm sorry about the last pull request. But now it should fit.

Fixes #8 

**Implemented:**
- [x] DataMatrixEncoder
- [x] Unit test

### CODE REVIEW

File: src/Barcoder/DataMatrix/DataMatrixEncoder.cs [hunk 1]
```diff
@@ -6,12 +6,23 @@ namespace Barcoder.DataMatrix
 {
     public static class DataMatrixEncoder
     {
-        public static IBarcode Encode(string content)
+        public static IBarcode Encode(string content, byte codeSize = 0)
```
Comment (huysentruitw) [inline src/Barcoder/DataMatrix/DataMatrixEncoder.cs]: `codeSize` seems to be the wrong name for this variable. I think I'd need to know the use-case in order to understand why this change is needed. I guess that you want to have a fixed size matrix for whatever content size, is that correct?

**Comment by Int32Overflow** [comment]
I need the option to create a DataMatrix code of a certain size independent of the data content.

There is the use case that a specific DataMatrix size is mandatory, but the data content would fit into a smaller DataMatrix code. (This is allowed according to specification)

**Comment by Int32Overflow** [comment]
@huysentruitw  Do you understand what I'm trying to do?

File: src/Barcoder/DataMatrix/DataMatrixEncoder.cs (hunk 1 above)
Comment (huysentruitw) [reply src/Barcoder/DataMatrix/DataMatrixEncoder.cs]: After understanding why this is needed, perhaps `int? fixedNumberOfRows = null` would be better as parameter.

File: src/Barcoder/DataMatrix/DataMatrixEncoder.cs [hunk 2]
```diff
@@ -6,12 +6,23 @@ namespace Barcoder.DataMatrix
...
         {
             var data = EncodeText(content);
 
-            CodeSize size = CodeSizes.All.FirstOrDefault(x => x.DataCodewords >= data.Length)
-                ?? throw new InvalidOperationException("Too much data to encode");
+            CodeSize size;
```
Comment (huysentruitw) [inline src/Barcoder/DataMatrix/DataMatrixEncoder.cs]: This logic is getting a little bit too big for this `Encode` method and asks to be split off.

Methods could be:

```
private static CodeSize GetSmallestCodeSizeForData(int dataLength)
{
    return CodeSizes.All.FirstOrDefault(x => x.DataCodewords >= dataLength)
        ?? throw new InvalidOperationException($"No code size found that fits {dataLength} codewords");
}

private static CodeSize GetFixedCodeSizeForData(int fixedNumberOfRows, int dataLength)
{
    CodeSize codeSize = CodeSizes.All.FirstOrDefault(x => x.Rows == fixedNumberOfRows)
        ?? throw new InvalidOperationException($"No code size found with fixed number of rows {fixedNumberOfRows}");
    if (size.DataCodewords < dataLength)
        throw new ArgumentException($"The fixed code size does not fit {dataLength} codewords");
    return codeSize;
}
```

Then in `Encode`:

```
CodeSize size = fixedNumberOfRows.HasValue
    ? GetFixedCodeSizeForData(fixedNumberOfRows.Value, data.Length)
    : GetSmallestCodeSizeForData(data.Length);
```

File: tests/Barcoder.Tests/DataMatrix/DataMatrixEncoderTests.cs [hunk 3]
```diff
@@ -68,6 +68,42 @@ public void Encode_ValidContent_ShouldEncodeDataMatrixCodeCorrectly()
...
+                #...##.####...
+                #..........#.#
+                #.###..##.....
+                ###.##.#.#####
+                #.####...#..#.
+                #.###..#.##.##
+                #..##.######..
+                ##############
+            ");
+            // Act
```
Comment (huysentruitw) [inline tests/Barcoder.Tests/DataMatrix/DataMatrixEncoderTests.cs:92]: Add new-line above this comment.

File: tests/Barcoder.Tests/DataMatrix/DataMatrixEncoderTests.cs [hunk 4]
```diff
@@ -68,6 +68,42 @@ public void Encode_ValidContent_ShouldEncodeDataMatrixCodeCorrectly()
...
+            var dataMatrix = DataMatrixEncoder.Encode(content, 14) as DataMatrixCode;
+            // Assert
```
Comment (huysentruitw) [inline tests/Barcoder.Tests/DataMatrix/DataMatrixEncoderTests.cs:95]: Add new-line above this comment.

**Review by huysentruitw — CHANGES_REQUESTED** [review]

File: src/Barcoder/DataMatrix/DataMatrixEncoder.cs [hunk 5]
```diff
@@ -6,12 +6,13 @@ namespace Barcoder.DataMatrix
 {
     public static class DataMatrixEncoder
     {
-        public static IBarcode Encode(string content)
+        public static IBarcode Encode(string content, byte fixedNumberOfRows = 0)
```
Comment (huysentruitw) [inline src/Barcoder/DataMatrix/DataMatrixEncoder.cs]:
```suggestion
        public static IBarcode Encode(string content, int? fixedNumberOfRows = null)
```

Public API's better use `int` instead of `byte`. Also, a nullable int better defines the 'optional' behavior of this parameter.

File: src/Barcoder/DataMatrix/DataMatrixEncoder.cs [hunk 6]
```diff
@@ -6,12 +6,13 @@ namespace Barcoder.DataMatrix
...
         {
             var data = EncodeText(content);
 
-            CodeSize size = CodeSizes.All.FirstOrDefault(x => x.DataCodewords >= data.Length)
-                ?? throw new InvalidOperationException("Too much data to encode");
+            CodeSize size = fixedNumberOfRows > 0
```
Comment (huysentruitw) [inline src/Barcoder/DataMatrix/DataMatrixEncoder.cs]:
```suggestion
            CodeSize size = fixedNumberOfRows.HasValue
```

File: src/Barcoder/DataMatrix/DataMatrixEncoder.cs [hunk 7]
```diff
@@ -6,12 +6,13 @@ namespace Barcoder.DataMatrix
...
+                ? GetFixedCodeSizeForData(fixedNumberOfRows, data.Length)
```
Comment (huysentruitw) [inline src/Barcoder/DataMatrix/DataMatrixEncoder.cs]:
```suggestion
                ? GetFixedCodeSizeForData(fixedNumberOfRows.Value, data.Length)
```

File: src/Barcoder/DataMatrix/DataMatrixEncoder.cs [hunk 8]
```diff
@@ -21,6 +22,21 @@ public static IBarcode Encode(string content)
             return code;
         }
 
+        private static CodeSize GetFixedCodeSizeForData(int fixedNumberOfRows, int dataLength)
+        {
+            CodeSize codeSize = CodeSizes.All.FirstOrDefault(x => x.Rows == fixedNumberOfRows)
+                ?? throw new InvalidOperationException($"No code size found with fixed number of rows {fixedNumberOfRows}");
+            if (codeSize.DataCodewords < dataLength)
+                throw new ArgumentException($"The fixed code size does not fit {dataLength} codewords");
```
Comment (huysentruitw) [inline src/Barcoder/DataMatrix/DataMatrixEncoder.cs]:
```suggestion
                throw new InvalidOperationException($"The fixed code size does not fit {dataLength} codewords");
```

**Review by huysentruitw — CHANGES_REQUESTED** [review]

**Review by Int32Overflow — COMMENTED** [review]
Done 👍

**Review by huysentruitw — APPROVED** [review]
